import Head from 'next/head'

const CustomHeader = () => {
  return (
    <div>
      <Head>
        <title>Code Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export default CustomHeader
