import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { FaGoogle } from 'react-icons/fa'
import { FaGithub } from 'react-icons/fa'

const SignUp = () => {
  return (
    <>
      <Head>
        <title>Code Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-6 md:mt-28">
        <div className="md:flex mt-6 justify-around items-center ">
          <Image
            className="hidden md:flex"
            height={500}
            width={500}
            src={'/assets/images/ai.png'}
            alt={'ai'}
          ></Image>
          <div className="p-6 justify-center md:w-5/12">
            <h1 className="text-center font-semibold text-lg">
              CODE HUB SIGN UP
            </h1>
            <div className="grid">
              <input
                className={`p-3 my-2 bg-slate-100 dark:bg-zinc-700`}
                type="text"
                placeholder="Username"
              />
              <input
                className={`p-3 my-2 bg-slate-100 dark:bg-zinc-700`}
                type="text"
                placeholder="Birthdate"
              />
              <input
                className={`p-3 my-2 bg-slate-100 dark:bg-zinc-700`}
                type="email"
                placeholder="Email"
              />
              <input
                className={`p-3 my-2 bg-slate-100 dark:bg-zinc-700`}
                type="password"
                placeholder="Password"
              />
            </div>
            <div className="text-white bg-black dark:bg-slate-600 p-4 text-center my-8 rounded-lg cursor-pointer">
              Sign Up
            </div>
            <h1 className="text-center text-sm">
              Have an account?{' '}
              <Link href={'/auth'}>
                <span className="text-black dark:text-green-300 font-semibold">
                  Sign In
                </span>
              </Link>
            </h1>
          </div>
        </div>
      </div>
    </>
  )
}
export default SignUp
