import Head from 'next/head'
import { FaGoogle } from 'react-icons/fa'
import { FaGithub } from 'react-icons/fa'
import Image from 'next/image'
import Link from 'next/link'
import { auth } from '../firebase'
import { GoogleAuthProvider, signInWithPopup } from 'firebase/auth'
import { useRouter } from 'next/router'

const SignIn = () => {
  const router = useRouter()
  const googleAuth = new GoogleAuthProvider()
  const handleSignIn = async () => {
    await signInWithPopup(auth, googleAuth).then(() => {
      router.push('/')
    })
  }

  return (
    <>
      <Head>
        <title>Code Hub</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mt-6 md:mt-28">
        <div className="md:flex mt-6 justify-around items-center ">
          {/* <Image
            className="hidden md:flex"
            height={500}
            width={500}
            src={'/assets/images/ai.png'}
            alt={'ai'}
          ></Image> */}
          <div className="p-6 justify-center md:w-5/12">
            <h1 className="text-center font-semibold text-lg">
              CODE HUB SIGN IN
            </h1>
            <div className="grid">
              <input
                className={`p-3 my-2 bg-slate-100 dark:bg-zinc-700`}
                type="email"
                placeholder="Email"
              />
              <input
                className={`p-3 my-2 bg-slate-100 dark:bg-zinc-700`}
                type="password"
                placeholder="Password"
              />
            </div>
            <h1 className="text-xs py-1 cursor-pointer">Forgot Password?</h1>
            <div className="flex justify-between items-center mt-6 ">
              <div
                onClick={handleSignIn}
                className="flex w-full text-white items-center rounded-lg bg-black dark:bg-slate-600 transition duration-500 dark:hover:bg-slate-300 hover:bg-slate-400 p-4 justify-between cursor-pointer"
              >
                <h1>Google Account</h1>
                <FaGoogle size={'20'} />
              </div>
              <div className="p-4 ml-6 cursor-pointer rounded-lg text-white bg-black dark:bg-slate-600 transition duration-500 dark:hover:bg-slate-300 hover:bg-slate-400 ">
                <FaGithub size={'20'} />
              </div>
            </div>
            <div className="text-white bg-black dark:bg-slate-600 p-4 text-center my-8 rounded-lg cursor-pointer">
              Sign In
            </div>
            <h1 className="text-center text-sm">
              Don't have an account?{' '}
              <Link href={'/auth/signup'}>
                <span className="text-black dark:text-green-300 font-semibold">
                  Sign Up
                </span>
              </Link>
            </h1>
          </div>
        </div>
      </div>
    </>
  )
}
export default SignIn
